name: Test

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install esy
        run: npm install -g esy@0.6.4

      - name: Create esy wrapper
        run: |
          echo '{
            "esy": {
              "build": "pkg-config --cflags libseccomp"
            },
            "dependencies": {
              "esy-libseccomp": "github:'"${GITHUB_REPOSITORY}"'#'"${GITHUB_SHA}"'"
            }
          }' > test.json

      - name: Build and run test
        run: esy @test
